# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-24 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='基金名称')),
                ('code', models.CharField(max_length=200, verbose_name='基金代码')),
                ('pe_low', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='市盈率低估值')),
                ('pe_normal', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='市盈率正常值')),
                ('pe_high', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='市盈率高估值')),
                ('pe', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='估值')),
            ],
            options={
                'verbose_name': '基金信息',
                'verbose_name_plural': '基金信息',
            },
        ),
        migrations.CreateModel(
            name='FundPartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='股票名称')),
                ('code', models.CharField(max_length=200, verbose_name='股票代码')),
                ('ratio', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='占比')),
                ('pe_ttm', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='TTM市盈率')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.FundInfo', verbose_name='所述基金')),
            ],
            options={
                'verbose_name': '基金成分股',
                'verbose_name_plural': '基金成分股',
            },
        ),
    ]
