# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-24 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundpartinfo',
            old_name='fund_id',
            new_name='fund',
        ),
    ]
