# Generated by Django 3.1.5 on 2021-01-24 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20210124_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fundpartinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
